packageExtensions:
  "@napi-rs/lzma-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": "^1.7.1"
      "@emnapi/runtime": "^1.7.1"
  "@napi-rs/tar-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": "^1.7.1"
      "@emnapi/runtime": "^1.7.1"
  "@napi-rs/wasm-tools-wasm32-wasi@*":
    dependencies:
      "@emnapi/core": "^1.7.1"
      "@emnapi/runtime": "^1.7.1"
