/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Cursor {
  has(pointer: string): Promise<boolean>
  get(pointer: string): Promise<unknown>
  get key(): string | number | null
  iter(pointer: string): CursorIter
  walk(pointer: string): CursorWalk
  cacheStats(): CacheStats
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class CursorIter {
  [Symbol.asyncIterator](): AsyncGenerator<any, void, undefined>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class CursorWalk {
  [Symbol.asyncIterator](): AsyncGenerator<Cursor, void, undefined>
}

export interface BoteOptions {
  /**
   * Maximum number of source chunks held resident at once. Each slot
   * accounts for one chunk's bytes plus its bitmaps. Defaults to 512.
   */
  maxResidentChunks?: number
}

/**
 * Live snapshot of the session's chunk-cache occupancy. The cache is
 * shared by every cursor derived from one `open()` call, so any cursor
 * reports the same figures. `residentBytes + bitmapBytes` is the total
 * native memory held for source data and stays at or below `ceilingBytes`
 * regardless of document size - the library's bounded-memory contract.
 */
export interface CacheStats {
  residentBytes: number
  bitmapBytes: number
  residentChunks: number
  ceilingBytes: number
}

export declare function heapProfilePeakBytes(): number

export declare function heapProfileStart(filePath?: string | undefined | null): void

export declare function heapProfileStop(): void

/**
 * Build a [`Cursor`] from a JS source object.
 *
 * The `source` argument must be a JS object with:
 *   - `size: number`                 total source size in bytes
 *   - `read(args): Promise<number>`  `args.offset: number`, `args.buf: Uint8Array`;
 *                                    JS writes bytes into `args.buf` and resolves
 *                                    with the number of bytes written
 *   - `chunkBytes?: number`          preferred read granularity in bytes (multiple of 64, optional)
 */
export declare function open(source: { size: number; chunkBytes?: number; read: (args: ReadArgs) => Promise<number> }, options?: BoteOptions | undefined | null): Cursor

/**
 * Arguments passed to the JS `read(args)` callback.
 *
 * We funnel `(offset, buf)` through a single object so the napi-rs
 * `ThreadsafeFunction` only has to model a single argument - keeping the
 * type signature in Rust simple. The TS facade wraps the user's
 * `read(offset, buf)` API into this shape.
 *
 * `buf` is an external `Uint8Array` view over a Rust-owned heap buffer of
 * `chunk_size` bytes; JS writes into it and resolves the returned promise
 * with the number of bytes written. JS must not retain a reference to `buf`
 * or read from it after that promise resolves - see [`JsSource::read`] for
 * the ownership protocol.
 */
export interface ReadArgs {
  offset: number
  buf: Uint8Array
}
