/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Cursor {
  has(path: Array<string | number>): Promise<boolean>
  get(path: Array<string | number>): Promise<string | undefined>
  iter(path: Array<string | number>, options: IterArgs): CursorIter
  hop(path: Array<string | number>): Promise<Cursor | null>
}

/**
 * This type implements JavaScript's async iterable protocol.
 * It can be used with `for await...of` loops.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_async_iterator_and_async_iterable_protocols
 */
export declare class CursorIter {
  [Symbol.asyncIterator](): AsyncGenerator<string, void, undefined>
}

export declare function heapProfilePeakBytes(): number

export declare function heapProfileStart(filePath?: string | undefined | null): void

export declare function heapProfileStop(): void

/**
 * Options for `iter`. A `#[napi(object)]` so the facade can grow it without
 * changing the method's arity.
 */
export interface IterArgs {
  /** Serialized projection IR (see `select.rs`); `None` yields the whole child. */
  selectIr?: string
  /** Items yielded per iteration. */
  batch: number
  /**
   * Stitch each yield as a `[key, value]` tuple instead of a bare value. The key
   * is the member name for objects (a JSON string) and the element index for
   * arrays (a JSON number).
   */
  withKey?: boolean
}

export type JsonFaultCode =  'malformed_json'|
'unexpected_eof';

/** Arguments passed to the JS `read(args)` callback. */
export interface JsReadArgs {
  offset: number
  length: number
}

/**
 * Value the JS `read(args)` callback resolves to: the bytes plus an
 * end-of-stream flag. `eof` lets an unknown-size source declare where the data
 * ends; for a sized source it's ignored (the engine already knows the end).
 */
export interface JsReadResult {
  data: Uint8Array
  eof: boolean
}

/**
 * Build a [`Cursor`] from a JS source object:
 *   - `size?: number` total source size in bytes; omit for a forward source
 *     whose end is discovered from `read`'s `eof`
 *   - `read(args): Promise<ReadResult>` (`args.offset`, `args.length`); resolves
 *     to `{ data, eof }` where `data.byteLength` is the actual count read
 *     (`<= length`) and `eof` marks end-of-stream
 *   - `chunkBytes: number` read granularity (whole, multiple of 64)
 *   - `indexCacheEntries?: number` structural-index cache slot budget (0 disables; default 1024)
 *   - `objectMemberCap?: number` max tabled members per object (0 disables; default unbounded)
 *   - `arrayIndexInterval?: number` element stride between array members (0 disables; default 16)
 */
export declare function open(source: { size?: number; chunkBytes: number; indexCacheEntries?: number; objectMemberCap?: number; arrayIndexInterval?: number; read: (args: ReadArgs) => Promise<ReadResult> }): Cursor

export type PathFaultCode =  'through_scalar'|
'scalar_target'|
'wrong_kind';

export type SourceFaultCode =  'source_io';
